# Generated by Django 3.1 on 2020-09-08 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('dni', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50, verbose_name='nombres')),
                ('date_joined', models.DateField(default=datetime.datetime(2020, 9, 8, 18, 3, 53, 940063), verbose_name='Fecha de Registro')),
                ('age', models.PositiveIntegerField()),
                ('married', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
    ]
